### ISSUE TITLE
Data Model Review Meeting Notes on 28/06/2016

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal-3.0#9] opened 2016-06-28 09:21 UTC
From Madhavi's Notes:
*\* Data model Review
- NOC role is not added in Abstract Entity Types
- Change abbriviation to Abbreviated in Abstract Entity Types
- Section 4: Relations and cardinality constraints over entity types
  change the first note description with the following equation:  
  if s1.user = s2.user -> s1.role != s2.role
- Attributes can be defined in the object model. 
- Assumptions need to be numbered.
- objects and methods are used in assumptions need to remove them
- Relations are wrongly defined. It is already defined. Need to remove them from Primary Entity Sets.
- In Referrential Integraty,
  user-set
  admin-user-set = { u E user-set | admin E roles(u)} admin-user-set != null 
  
  In relations,
  role need to be changed to roles
- Effect:
  assume u = new User()
  1. roles(u) = {guest}
  2. user-set = user-set U {u}
- trasability should be there for this referrential intigrity. 
- =AuditEntry= Entity is not there in the DataModel.
- Audit entry parameters need to be defined.
- =current session id= need to be changed to =current session user id=
- =updating-entry-id= need to be changed to =updated-entry-id=
- Audit entry should be only able to read the data.
- Need to have active-user-set, user-set, logged-in-users
  active-user-set C user-set, logged-in-users C active-user-set
- In AuditEntry, operations with parameters and its timestamp need to
  be captured so that AuditEntry should be used to reconstruct the
  database.
- All Artifacts should be soft delete.
- In Delete user, in referential integraty, "which" should be changed to "that"
- Status need to defined in the model. Status should be "upcoming", "completed", "Approved", "Pending for Approval" etc.
  Also fix the diagram.
- Workshop should cancelled before the workshop date.
- Workshop cannot be cancelled after its date has been passed. It means workshop is not done.

**Comment by madhavipuliraju** [comment] 2016-06-28 09:25
From Thirumal's Notes:

----NEW CHANGES for meeting on 28th June ----

--Write minutes of meeting
--In Abstract Entity Types, change 'abbreviation' to 'abbreviated'
--add NOC in roles list
--replace NOTE 1 in relations with logical statements
--add traceability
--number all bullet points
--change notation for relations
--in referential integrity, change the integrity constraint for admin-user
--make effect for add user more specific by using variables
--add delete-user implementation, and make it more specific
--change audit trail implementation, as well as data-model
--change 'which' to 'that' in remarks for delete user
--define Status entity
--change workshop workflow diagram
--add 'completed' state in the workshop workflow diagram

**Comment by madhavipuliraju** [comment] 2016-06-28 09:47
Meeting MoM:
The following are the four main action items of this meeting:
1) Traceability: https://github.com/vlead/outreach-portal-3.0/issues/13
2) Formal Notations: https://github.com/vlead/outreach-portal-3.0/issues/12
3) Status for Workshop Link: https://github.com/vlead/outreach-portal-3.0/issues/10
4) Audit Entry Link: https://github.com/vlead/outreach-portal-3.0/issues/11

**Comment by travula** [comment] 2016-06-28 13:17
This is a duplicate of #16

**Closed as completed by travula** 2016-06-28 13:17 UTC
Labels: duplicate
